### ISSUE TITLE
get_cids() does not support special characters

### ISSUE THREAD

**Issue by KingFunk** [pyrfume/pyrfume#14]
Special Greek characters common to molecules are not recognized by get_CID() and must be converted to their generic name manually.
For example, β-ionone must be changed to beta-ionone.

**Comment by rgerkin** [comment]
@KingFunk This may be an issue with URL-escaping these names/symbols.  I will try to fix in the next release.

**Comment by rgerkin** [comment]
@KingFunk
Just fixed in 3ea2f8db9c7bd0f1e015005868953013a51692ea.  Are you working from development code or from a PyPI release?  If working from development code, just `git pull` to get the fix.
