### ISSUE TITLE
Quantum Computing Readyness

### ISSUE THREAD

**Issue by contrebande-labs** [pyrfume/pyrfume#23]
Hi guys,

Have some of you given a thought or two about reformulating the problems, algorithms and methods of computational olfaction to benefit from the recent quantum computing advances (especially [IBM's](https://www.youtube.com/watch?v=-qBrLqvESNM)). Are you aware of any efforts to port GNNs, olfactive QSAR, molecule simulation (such as 3D conformer and vibration spectrum generation) to environments and languages such as [Qiskit](https://qiskit.org/) and [OpenQasm](https://github.com/qiskit/openqasm)?

Thanks.

**Comment by rgerkin** [comment]
Not on the current roadmap.
