### ISSUE TITLE
Develop manifest format

### ISSUE THREAD

**Issue by rgerkin** [pyrfume/pyrfume#7]
This would describe the information for each dataset:
- [x] A slug representing the dataset name
- [x] Licensing status
- [ ] Number of unique odorants
- [x] etc.

**Comment by joelmainland** [comment]
Do you want doi field to have the "http:" part, or just the doi? I see both versions.

**Comment by rgerkin** [comment]
@joelmainland I could go either way.  The http is unnecessary but does make it copy-pastable into a browser.

**Comment by rgerkin** [comment]
Implemented in all archives.
